application: cqdtest
version: dev
runtime: php
api_version: 1
threadsafe: true

##########################################
handlers:
##########################################

- url: /js
  static_dir: public/js

- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

##########################################

- url: /.*
  script: router.php
