application: cqdtest
version: dev
runtime: php55
api_version: 1
threadsafe: true

##########################################
handlers:
##########################################

- url: /js
  static_dir: public/js

- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

##########################################

- url: /
  script: public/strip.php

- url: /strip/.*
  script: public/strip.php

- url: /atom/
  script: public/atom.php

- url: /sitemap.xml
  script: public/sitemap.php
